### ISSUE TITLE
Castero doesn't consider Youtube feeds as valid rss

### ISSUE THREAD

**Issue by taziden** [xgi/castero#107]
Hi,
I'm not sure if this is an issue per se but I'm trying to import a youtube channel rss feed into castero and I encounter the following traceback:

`Traceback (most recent call last):
  File "/home/taziden/.local/bin/castero", line 5, in <module>
    from castero.__main__ import main
  File "/home/taziden/.local/pipx/venvs/castero/lib/python3.8/site-packages/castero/__main__.py", line 159, in <module>
    main()
  File "/home/taziden/.local/pipx/venvs/castero/lib/python3.8/site-packages/castero/__main__.py", line 92, in main
    import_subscriptions(vars(args)['import'], database)
  File "/home/taziden/.local/pipx/venvs/castero/lib/python3.8/site-packages/castero/__main__.py", line 27, in import_subscriptions
    for generated in subscriptions.parse():
  File "/home/taziden/.local/pipx/venvs/castero/lib/python3.8/site-packages/castero/subscriptions.py", line 136, in parse
    feed = Feed(url=entry.attrib['xmlUrl'])
  File "/home/taziden/.local/pipx/venvs/castero/lib/python3.8/site-packages/castero/feed.py", line 83, in __init__
    self._validate_feed()
  File "/home/taziden/.local/pipx/venvs/castero/lib/python3.8/site-packages/castero/feed.py", line 179, in _validate_feed
    raise FeedStructureError("XML document is not an RSS feed")
castero.feed.FeedStructureError: XML document is not an RSS feed
`
Example feed: https://www.youtube.com/feeds/videos.xml?channel_id=UCSULDz1yaHLVQWHpm4g_GHA

**Comment by xgi** [comment]
I looked into the structure of those youtube feeds and it's definitely not RSS, so this isn't an issue with the parser. Theoretically it's not *too* different, but adding support for this format specifically would require rewriting quite a bit of code since there are many (imo reasonable) assumptions that feeds are valid RSS. This is something I might add in the future, but I don't think I'll plan on doing it at the moment.

**Comment by Inrin** [comment]
It's not RSS but an Atom-Feed.
You may use python-feedparser, to read RSS and Atom feeds.

**Comment by tyjak** [comment]
Would be very nice to have ATOM feed support :)
