### ISSUE TITLE
Arch with Itunes OPML

### ISSUE THREAD

**Issue by revchain** [xgi/castero#136]
I'm getting this error while importing an iTunes .OPML on Arch with Konsole. I don't know if it's me or iTunes. I'm using the AUR version, tried both versions, same problem. Thanks.

Traceback (most recent call last):
  File "/usr/bin/castero", line 33, in <module>
    sys.exit(load_entry_point('castero==0.8.1', 'console_scripts', 'castero')())
  File "/usr/bin/castero", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/castero/__main__.py", line 160, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/castero/__main__.py", line 95, in main
    import_subscriptions(vars(args)['import'], database)
  File "/usr/lib/python3.8/site-packages/castero/__main__.py", line 36, in import_subscriptions
    print("Added \"%s\" with %d episodes" % (str(feed), len(episodes)))
  File "/usr/lib/python3.8/site-packages/castero/feed.py", line 108, in __str__
    assert self._title is not None
AssertionError

**Comment by xgi** [comment]
Would you be able to upload the contents of your OPML file? You can do so here (or anywhere else you prefer): https://gist.github.com

It seems like the OPML iTunes gave you is missing the title for a feed, which theoretically should be required. I might be able to handle this a bit more gracefully but I'm curious how the file itself looks.

**Comment by revchain** [comment]
Ok here's a link. Thanks.. https://gist.github.com/revchain/a42b550c822027928107ba2007887507

**Comment by xgi** [comment]
Fixed with #139. Thanks!
