### ISSUE TITLE
Cannot import pocket casts opml

### ISSUE THREAD

**Issue by nadir-yttrium** [xgi/castero#176]
Hi, 

first, let me thank you for this awesome tool. 

My issue: When I try to import my [podcasts.opml](https://gist.github.com/nadir-yttrium/87c739aa5006fec4241c42880e506a1b) that I exported from PocketCasts I get the following error:

> ❯ castero --import ./podcasts.opml
Added "On the Media" with 120 episodes
Traceback (most recent call last):
  File "/usr/bin/castero", line 33, in <module>
    sys.exit(load_entry_point('castero==0.9.3', 'console_scripts', 'castero')())
  File "/usr/bin/castero", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/castero/__main__.py", line 161, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/castero/__main__.py", line 96, in main
    import_subscriptions(vars(args)['import'], database)
  File "/usr/lib/python3.9/site-packages/castero/__main__.py", line 30, in import_subscriptions
    for generated in subscriptions.parse():
  File "/usr/lib/python3.9/site-packages/castero/subscriptions.py", line 136, in parse
    feed = Feed(url=entry.attrib['xmlUrl'])
  File "/usr/lib/python3.9/site-packages/castero/feed.py", line 98, in __init__
    self._parse_metadata()
  File "/usr/lib/python3.9/site-packages/castero/feed.py", line 315, in _parse_metadata
    self._copyright = copyright_tag.text.strip()
AttributeError: 'NoneType' object has no attribute 'strip'

My setup:

- OS: Arch and Raspberry OS
- Packages: 
    - Arch: Both castero-git and castero from the Aur have the same issue
    - Raspberry OS: Used pip 21.1.3
- python: 3.9
- castero: 0.9.3

**Comment by xgi** [comment]
This is fixed with #177 - thanks for providing your .opml! The issue was just that one of your feeds didn't have a copyright value, which the parser expected.

I won't be ticking the castero version for some time, but you can get the update if you use castero-git (or manually clone+install from the repo). Thanks!
