### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by quoidautre** [xgi/castero#201]
Hello,

I've just install (with pip 22.3.1) Castero on Windows 10, and Python 3.9.2rc1.

If I run, there's this error message : 

```
Traceback (most recent call last):
  File "c:\users\ME\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\ME\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ME\AppData\Local\Programs\Python\Python39\Scripts\castero.exe\__main__.py", line 4, in <module>
  File "c:\users\ME\appdata\local\programs\python\python39\lib\site-packages\castero\__main__.py", line 149, in <module>
    main()
  File "c:\users\ME\appdata\local\programs\python\python39\lib\site-packages\castero\__main__.py", line 122, in main
    redirect_stderr()
  File "c:\users\ME\appdata\local\programs\python\python39\lib\site-packages\castero\__main__.py", line 65, in redirect_stderr
    libc = ctypes.CDLL(None)
  File "c:\users\ME\appdata\local\programs\python\python39\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable
```

Have you an idea please ?
Thanks

F.

**Comment by Jvcon** [comment]
I met the same problem.

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\NAME\scoop\apps\python\current\Scripts\castero.exe\__main__.py", line 4, in <module>
  File "C:\Users\NAME\scoop\apps\python\current\Lib\site-packages\castero\__main__.py", line 149, in <module>
    main()
  File "C:\Users\NAME\scoop\apps\python\current\Lib\site-packages\castero\__main__.py", line 122, in main
    redirect_stderr()
  File "C:\Users\NAME\scoop\apps\python\current\Lib\site-packages\castero\__main__.py", line 65, in redirect_stderr
    libc = ctypes.CDLL(None)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\NAME\scoop\apps\python\current\Lib\ctypes\__init__.py", line 366, in __init__
    if '/' in name or '\\' in name:
       ^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by CorAnna** [comment]
I also have the same problem

**Comment by fedeis** [comment]
Same problem, up :)

**Comment by GuiReboucas** [comment]
Same Problem
