### ISSUE TITLE
runtime dependency on python-vlc

### ISSUE THREAD

**Issue by rookiejet** [xgi/castero#29]
Castero (0.41) still requires python-vlc when run with only python-mpv dependency met.
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/castero", line 11, in <module>
    load_entry_point('castero==0.4.1', 'console_scripts', 'castero')()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.6/site-packages/castero/__main__.py", line 83, in <module>
    main()
  File "/usr/lib64/python3.6/site-packages/castero/__main__.py", line 56, in main
    display = Display(stdscr, feeds)
  File "/usr/lib64/python3.6/site-packages/castero/display.py", line 94, in __init__
    self._load_players()
  File "/usr/lib64/python3.6/site-packages/castero/display.py", line 161, in _load_players
    p_mod = importlib.import_module("castero.players.%s" % name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib64/python3.6/site-packages/castero/players/vlcplayer.py", line 3, in <module>
    import vlc
ModuleNotFoundError: No module named 'vlc'
```

config has `player = mpv` set.

**Comment by xgi** [comment]
This crash should be fixed as of fb1b578ea92e101775d1807b42eaa9692fadb265.

Also, perhaps this is an adjacent concern, but I will say that it is intentional for all external player libraries to be installed by default. Otherwise we would have to ask users to manually install libraries after changing the config, which I don't want to do.

Thanks for the help!

**Comment by rien333** [comment]
@xgi vlc is quite heavy duty/large and virtually useless to have if you already have mpv.    I'm pretty sure making all media players required is neither common, nor needed. 

> Otherwise we would have to ask users to manually install libraries after changing the config, which I don't want to do.

Could you elaborate? I don't follow. [mps-youtube](https://github.com/mps-youtube/mps-youtube), a python TUI app that supports a wide variety of media players, just tells you "hey, your current media player configuration is not supported, please install the required files (or change your config)".  You could easily wrap the python `import vlc/mpv` statement in a `try` block and inform the user about what needs to be done. Or just go with what the user already has installed if it's found, and error out otherwise.

Some background: `python-vlc` pulls in a ton of dependencies on my system.

**Comment by xgi** [comment]
@rien333 I created #62 to address this concern, although I don't currently have a clear plan for dealing with it. Thanks!
